name: Misspells
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: reviewdog fixer
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
      - name: sobolevn fixer
        uses: sobolevn/misspell-fixer-action@master

